apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
spec:
  containers:
  - name: nginx
    image: nginx

--- # Pod Affinity Example
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      # Pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname"
  