apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: pod-3
spec:
  containers:
  - name: nginx
    image: nginx

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      # Pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-1
            - pod-2
        topologyKey: "kubernetes.io/hostname"