apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-toleration-demo
  labels:
    project: roboshop
    purpose: toleration-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: toleration-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: toleration-demo
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-21-195.ec2.internal
      containers:
        - name: nginx
          image: nginx:latest
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"
        